### ISSUE TITLE
Commented Out Tests

### ISSUE THREAD

**Issue by justanr** [jidn/flask-resteasy#1]
I noticed a few tests were commented out, why is that? Should they be deleted? Or marked to only be run sometimes?

**Comment by jidn** [comment]
I removed that test in c0f9cab.  It was testing for pretty printed JSON output in debug.  That never was a feature and could better be handled as a decorator in any case.  Thanks for helping clean out the deadwood.

**Comment by justanr** [comment]
There's also this bugger:

https://github.com/jidn/flask-resteasy/blob/c0f9cab76135e966cb5dacfe6f7f0c1bf8c94d57/tests/api.py#L39
