### ISSUE TITLE
Is there a way to make the JSON encoder pretty print?

### ISSUE THREAD

**Issue by jammarsh** [jidn/flask-resteasy#2]
Thanks for the work

**Comment by jidn** [comment]
Sure.  JSONResponse takes any unknown keyword arguments and passes them on to the encoder when called.  This allows you to do something like 

responder = JSONResponse(sort_keys=True, indent=4, separators=(',', ':'))
app = Flask(**name**)
api = Api(app, response=responder)

Now it will be pretty printed.  I'll add some test cases as examples.
