### ISSUE TITLE
Error handlers

### ISSUE THREAD

**Issue by giancarlocp** [jidn/flask-resteasy#3]
I want to add Rest-API to a traditional app.
So i would like separate error handler.

> http://localhost:5000/a

This should response **html** 404 error

> http://localhost:5000/api/v1/a

And this should response **json** 404 error

``` python
from flask import Blueprint, Flask
app = Flask(__name__)

import flask_resteasy as rest
api_bp = Blueprint('api', __name__)
api = rest.Api(api_bp)

@api_bp.errorhandler(404)
def not_found(e):
    response = jsonify({'status': 404, 'error': 'not found',})
    response.status_code = 404
    return response

if __name__ == '__main__':
    app.register_blueprint(api_bp, url_prefix='/api/v1')
    app.run(debug=True)
```

So, due RestEasy hasn't 'errorhandler' attribute and doesn't inherit from Flask
`@api.errorhandler(404)`

> AttributeError: 'Api' object has no attribute 'errorhandler'

I try this too: `@api_db.errorhandler(404)`
This runs without error, but '/api/v1/a' returns **html**

How can i separate Blueprints errorhandler?

**Comment by jidn** [comment]
Error handling is handled at the app level.  Instead of api_bp.errorhandler, put it on the app.

See
http://flask.pocoo.org/docs/0.11/patterns/errorpages/
